'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, Minus, Plus, ShoppingBag } from 'lucide-react';
type Variant={id:string;weightLabel:string;cutOption:string|null;price:number;mrp:number;inStock:boolean};
const GUEST_CART_KEY='freash_guest_cart';
export default function AddToCartForm({weightLabels,cutOptions,variants}:{productSlug:string;weightLabels:string[];cutOptions:string[];variants:Variant[]}){const router=useRouter();const [weight,setWeight]=useState(weightLabels[0]);const [cut,setCut]=useState<string|null>(cutOptions[0]??null);const [qty,setQty]=useState(1);const [status,setStatus]=useState<'idle'|'adding'|'added'|'error'>('idle');const [error,setError]=useState<string|null>(null);const variant=variants.find(v=>v.weightLabel===weight&&v.cutOption===cut)||variants.find(v=>v.weightLabel===weight)||variants[0];const off=variant?Math.max(0,Math.round((1-variant.price/variant.mrp)*100)):0;async function add(go:boolean){if(!variant)return;setStatus('adding');setError(null);try{const res=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({variantId:variant.id,quantity:qty})});if(res.status===401){
        let existing:any[]=[]; try { existing=JSON.parse(localStorage.getItem(GUEST_CART_KEY)||'[]'); if(!Array.isArray(existing)) existing=[]; } catch { existing=[]; }
        const idx=existing.findIndex((x:any)=>x.variantId===variant.id);
        if(idx>=0) existing[idx].quantity=Math.min(20, existing[idx].quantity+qty);
        else existing.push({variantId:variant.id,quantity:qty,weightLabel:variant.weightLabel,cutOption:variant.cutOption,price:variant.price,mrp:variant.mrp});
        localStorage.setItem(GUEST_CART_KEY,JSON.stringify(existing));
        setStatus('added'); window.dispatchEvent(new Event('cart-updated')); if(go)router.push('/cart'); else setTimeout(()=>setStatus('idle'),1600); return;
      }const text=await res.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{}if(!res.ok){setError(body?.error??`Could not add to cart (${res.status})`);setStatus('error');return}setStatus('added');window.dispatchEvent(new Event('cart-updated'));if(go)router.push('/cart');setTimeout(()=>setStatus('idle'),1600)}catch{setError('Something went wrong. Please try again.');setStatus('error')}}return <div><div className="purchase-price">₹{variant?.price??0}{variant?.mrp?<span className="mrp">₹{variant.mrp}</span>:null}{off>0&&<span style={{fontSize:11,color:'var(--green)',marginLeft:9}}>{off}% OFF</span>}</div><div className="select-label">Weight</div><div className="choice-row">{weightLabels.map(w=><button type="button" key={w} onClick={()=>setWeight(w)} className={`choice ${weight===w?'selected':''}`}>{w}</button>)}</div>{cutOptions.length>0&&<><div className="select-label">Cut / preparation</div><div className="choice-row">{cutOptions.map(c=><button type="button" key={c} onClick={()=>setCut(c)} className={`choice ${cut===c?'selected':''}`}>{c}</button>)}</div></>}<div className="select-label">Quantity</div><div className="qty-control"><button type="button" onClick={()=>setQty(q=>Math.max(1,q-1))}><Minus size={14}/></button><span>{qty}</span><button type="button" onClick={()=>setQty(q=>Math.min(20,q+1))}><Plus size={14}/></button></div>{variant&&!variant.inStock&&<p style={{color:'var(--red)',fontSize:12,marginTop:12}}>This option is currently out of stock.</p>}{error&&<p style={{color:'var(--red)',fontSize:12,marginTop:12}}>{error}</p>}<div className="purchase-actions"><button type="button" disabled={!variant?.inStock||status==='adding'} className="add-btn" onClick={()=>add(false)}>{status==='added'?<><Check size={15}/> Added</>:<><ShoppingBag size={15}/> Add to Cart</>}</button><button type="button" disabled={!variant?.inStock||status==='adding'} className="buy-btn" onClick={()=>add(true)}>{status==='adding'?'Adding…':'Buy Now'}</button></div></div>}
